// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package go_micro_service_user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	MessageRequest
	MessageResponse
	RegisterRequest
	LoginRequest
	Response
	LoginResponse
*/
package go_micro_service_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageRequest struct {
}

func (m *MessageRequest) Reset()                    { *m = MessageRequest{} }
func (m *MessageRequest) String() string            { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()               {}
func (*MessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MessageResponse struct {
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
}

func (m *MessageResponse) Reset()                    { *m = MessageResponse{} }
func (m *MessageResponse) String() string            { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()               {}
func (*MessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MessageResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type RegisterRequest struct {
	Account  string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Code     string `protobuf:"bytes,4,opt,name=code" json:"code,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RegisterRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RegisterRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type LoginRequest struct {
	Account  string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Code     string `protobuf:"bytes,4,opt,name=code" json:"code,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type Response struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type LoginResponse struct {
	Msg   string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LoginResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageRequest)(nil), "go.micro.service.user.MessageRequest")
	proto.RegisterType((*MessageResponse)(nil), "go.micro.service.user.MessageResponse")
	proto.RegisterType((*RegisterRequest)(nil), "go.micro.service.user.RegisterRequest")
	proto.RegisterType((*LoginRequest)(nil), "go.micro.service.user.LoginRequest")
	proto.RegisterType((*Response)(nil), "go.micro.service.user.Response")
	proto.RegisterType((*LoginResponse)(nil), "go.micro.service.user.LoginResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0xb5, 0x6d, 0xaa, 0x75, 0xfc, 0x68, 0x19, 0x14, 0x42, 0x10, 0x94, 0x68, 0x8b, 0xa7, 0x3d,
	0xe8, 0xc1, 0x3f, 0xa1, 0x97, 0x68, 0xc1, 0x93, 0x10, 0x37, 0x43, 0x08, 0x25, 0xbb, 0x71, 0x27,
	0xb1, 0x3f, 0xc4, 0x3f, 0x2c, 0x49, 0x36, 0x4b, 0x15, 0xa3, 0xf6, 0xb6, 0x2f, 0xef, 0xcd, 0x7b,
	0x33, 0x93, 0x01, 0xa8, 0x98, 0x8c, 0x28, 0x8c, 0x2e, 0x35, 0x9e, 0xa6, 0x5a, 0xe4, 0x99, 0x34,
	0x5a, 0x30, 0x99, 0xf7, 0x4c, 0x92, 0xa8, 0xc9, 0x70, 0x06, 0xc7, 0x0f, 0xc4, 0x1c, 0xa7, 0x14,
	0xd1, 0x5b, 0x45, 0x5c, 0x86, 0x73, 0x98, 0xba, 0x2f, 0x5c, 0x68, 0xc5, 0x84, 0x08, 0x9e, 0xd4,
	0x09, 0xf9, 0x83, 0x8b, 0xc1, 0xf5, 0x7e, 0xd4, 0xbc, 0xc3, 0x35, 0x4c, 0x23, 0x4a, 0x33, 0x2e,
	0xc9, 0xd8, 0x4a, 0xf4, 0x61, 0x2f, 0x96, 0x52, 0x57, 0xaa, 0xb4, 0xca, 0x0e, 0x62, 0x00, 0x13,
	0x95, 0xc9, 0x95, 0x8a, 0x73, 0xf2, 0x87, 0x0d, 0xe5, 0x70, 0xcd, 0x15, 0x31, 0xf3, 0x5a, 0x9b,
	0xc4, 0x1f, 0xb5, 0x5c, 0x87, 0x5d, 0xb0, 0xb7, 0x11, 0xfc, 0x0c, 0x87, 0xf7, 0x3a, 0xcd, 0xd4,
	0xbf, 0x52, 0xb7, 0x72, 0x3e, 0x83, 0x89, 0x1b, 0x79, 0x06, 0xa3, 0x9c, 0x53, 0xeb, 0x58, 0x3f,
	0xc3, 0x3b, 0x38, 0xb2, 0xb9, 0x7d, 0x12, 0x3c, 0x81, 0x71, 0xa9, 0x57, 0xa4, 0xec, 0x8c, 0x2d,
	0xb8, 0xf9, 0x18, 0x82, 0xb7, 0x64, 0x32, 0xb8, 0xac, 0xfd, 0xdb, 0x95, 0xe1, 0x42, 0xfc, 0xf8,
	0x3f, 0xc4, 0xb7, 0x9d, 0x06, 0xe7, 0xbd, 0xba, 0xb6, 0x8b, 0x70, 0x07, 0x9f, 0x60, 0xdc, 0x34,
	0x86, 0x97, 0x3d, 0xda, 0xcd, 0x75, 0x05, 0x57, 0xbf, 0x8b, 0x9c, 0xeb, 0x0b, 0x1c, 0x3c, 0x92,
	0x4a, 0xec, 0x29, 0xe0, 0xbc, 0xa7, 0xec, 0xeb, 0xf1, 0x04, 0x8b, 0xbf, 0x64, 0x9d, 0xff, 0xeb,
	0x6e, 0x73, 0x96, 0xb7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x51, 0x28, 0xb6, 0x1b, 0xa4, 0x02,
	0x00, 0x00,
}
