// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package go_micro_service_user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	MessageRequest
	MessageResponse
	RegisterRequest
	LoginRequest
	RegisterResponse
	LoginResponse
*/
package go_micro_service_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageRequest struct {
}

func (m *MessageRequest) Reset()                    { *m = MessageRequest{} }
func (m *MessageRequest) String() string            { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()               {}
func (*MessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MessageResponse struct {
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
}

func (m *MessageResponse) Reset()                    { *m = MessageResponse{} }
func (m *MessageResponse) String() string            { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()               {}
func (*MessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MessageResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type RegisterRequest struct {
	Account  string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Code     string `protobuf:"bytes,4,opt,name=code" json:"code,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RegisterRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RegisterRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type LoginRequest struct {
	Account  string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Code     string `protobuf:"bytes,4,opt,name=code" json:"code,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type RegisterResponse struct {
	Msg       string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	IsSuccess bool   `protobuf:"varint,2,opt,name=is_success,json=isSuccess" json:"is_success,omitempty"`
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RegisterResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RegisterResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

type LoginResponse struct {
	Msg       string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	IsSuccess bool   `protobuf:"varint,2,opt,name=is_success,json=isSuccess" json:"is_success,omitempty"`
	Token     string `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	Nickname  string `protobuf:"bytes,4,opt,name=nickname" json:"nickname,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LoginResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LoginResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageRequest)(nil), "go.micro.service.user.MessageRequest")
	proto.RegisterType((*MessageResponse)(nil), "go.micro.service.user.MessageResponse")
	proto.RegisterType((*RegisterRequest)(nil), "go.micro.service.user.RegisterRequest")
	proto.RegisterType((*LoginRequest)(nil), "go.micro.service.user.LoginRequest")
	proto.RegisterType((*RegisterResponse)(nil), "go.micro.service.user.RegisterResponse")
	proto.RegisterType((*LoginResponse)(nil), "go.micro.service.user.LoginResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcb, 0x4e, 0xc3, 0x30,
	0x10, 0xa4, 0x6d, 0x0a, 0xed, 0xf2, 0x68, 0xb5, 0x02, 0x29, 0x8a, 0x84, 0x84, 0x02, 0x2d, 0x9c,
	0x7c, 0x80, 0x4f, 0xe0, 0x0a, 0x97, 0x14, 0x24, 0x2e, 0x80, 0x82, 0xbb, 0x8a, 0xac, 0xaa, 0x76,
	0xf1, 0x26, 0xf4, 0x63, 0xf8, 0x59, 0x94, 0xc4, 0x09, 0x0d, 0xa2, 0x14, 0xb8, 0x79, 0x3c, 0xb3,
	0xb3, 0x1e, 0xaf, 0x0d, 0x90, 0x31, 0x59, 0xb1, 0xb0, 0x26, 0x35, 0x78, 0x94, 0x18, 0x31, 0x57,
	0xd2, 0x1a, 0xc1, 0x64, 0xdf, 0x94, 0x24, 0x91, 0x93, 0xe1, 0x10, 0x0e, 0x6e, 0x89, 0x39, 0x4e,
	0x28, 0xa2, 0xd7, 0x8c, 0x38, 0x0d, 0x47, 0x30, 0xa8, 0x77, 0x78, 0x61, 0x34, 0x13, 0x22, 0x78,
	0xd2, 0x4c, 0xc9, 0x6f, 0x9d, 0xb4, 0x2e, 0xfa, 0x51, 0xb1, 0x0e, 0x97, 0x30, 0x88, 0x28, 0x51,
	0x9c, 0x92, 0x75, 0x95, 0xe8, 0xc3, 0x4e, 0x2c, 0xa5, 0xc9, 0x74, 0xea, 0x94, 0x15, 0xc4, 0x00,
	0x7a, 0x5a, 0xc9, 0x99, 0x8e, 0xe7, 0xe4, 0xb7, 0x0b, 0xaa, 0xc6, 0x39, 0xb7, 0x88, 0x99, 0x97,
	0xc6, 0x4e, 0xfd, 0x4e, 0xc9, 0x55, 0xb8, 0x6e, 0xec, 0xad, 0x34, 0x7e, 0x80, 0xbd, 0x1b, 0x93,
	0x28, 0xfd, 0xab, 0xae, 0x7f, 0x72, 0xbe, 0x86, 0xe1, 0x67, 0x24, 0x17, 0x7d, 0x08, 0x9d, 0x39,
	0x27, 0xce, 0x39, 0x5f, 0xe2, 0x31, 0x80, 0xe2, 0x67, 0xce, 0xa4, 0x24, 0xe6, 0x22, 0x4d, 0x2f,
	0xea, 0x2b, 0x9e, 0x94, 0x1b, 0xa1, 0x85, 0x7d, 0x77, 0xbc, 0x7f, 0x3a, 0xe0, 0x21, 0x74, 0x53,
	0x33, 0x23, 0xed, 0xce, 0x5c, 0x82, 0xc6, 0x15, 0x7a, 0xcd, 0x2b, 0xbc, 0x7c, 0x6f, 0x83, 0x77,
	0xcf, 0x64, 0xf1, 0x11, 0x7a, 0x55, 0x02, 0x1c, 0x8b, 0x6f, 0x27, 0x2e, 0xbe, 0x4c, 0x2d, 0x38,
	0xdf, 0xa8, 0x2b, 0x83, 0x84, 0x5b, 0x78, 0x07, 0xdd, 0x22, 0x1b, 0x9e, 0xae, 0xa9, 0x59, 0x1d,
	0x4c, 0x70, 0xf6, 0xb3, 0xa8, 0x76, 0x7d, 0x82, 0xdd, 0x09, 0xe9, 0xa9, 0x7b, 0x74, 0x38, 0x5a,
	0x53, 0xd6, 0x7c, 0xa6, 0xc1, 0x78, 0x93, 0xac, 0xf2, 0x7f, 0xd9, 0x2e, 0x3e, 0xc0, 0xd5, 0x47,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0xe0, 0x0f, 0x62, 0x0e, 0x03, 0x00, 0x00,
}
